version: '3'
services:

  bot:
    build: .
    image: bot:devel
    restart: on-failure
    container_name: abp_bot_container
    command: python3 main.py
    env_file: config/environment/docker
    volumes:
      - .:/app
      - static_data:/app/static

volumes:
  static_data:
