version: '3'
services:

  abp_db:
    image: mariadb:10.3
    env_file: config/environment/docker

  bot:
    build: .
    image: bot:devel
    restart: on-failure
    container_name: abp_bot_container
    command: make run
    env_file: config/environment/docker
    volumes:
      - .:/app
      - static_data:/app/static
    depends_on:
      - abp_db

volumes:
  static_data:
  